# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35cecbdbb1f4c0eaf1ac09d2687072ef4bb72052955b8bad7654d81512c9b5d3ef2cda8966628c4bc1f53792e46b894fda361822767e87dabad03e096367be2

test:
  secret_key_base: 9053b982c6c141d5808f859462497ba58a462124b87ffea35f831c3fef832b139d361b887a8f75ff46570ec6548cec2b95398ab9cf211834eca9cecb13195bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
